name: ci-docker

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps & run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -q

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login (Docker Hub)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push API (CPU)
      - name: Build & push API (CPU)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ronitshahu/traffic-sign-yolo:latest
            ronitshahu/traffic-sign-yolo:${{ github.sha }}

      # (Optional) Build & push API (GPU) if Dockerfile.gpu exists
      - name: Build & push API (GPU)
        if: ${{ hashFiles('Dockerfile.gpu') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.gpu
          push: true
          tags: |
            ronitshahu/traffic-sign-yolo-gpu:latest
            ronitshahu/traffic-sign-yolo-gpu:${{ github.sha }}

      # Build & push UI
      - name: Build & push UI
        uses: docker/build-push-action@v6
        with:
          context: ui
          file: ui/Dockerfile.ui
          push: true
          tags: |
            ronitshahu/traffic-sign-ui:latest
            ronitshahu/traffic-sign-ui:${{ github.sha }}

      # (Optional) Re-tag MLflow to your namespace
      - name: Pull & push MLflow (optional)
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker tag ghcr.io/mlflow/mlflow:latest ronitshahu/mlflow:latest
          docker push ronitshahu/mlflow:latest
